language: node_js

node_js:
 - "6"

env:
# Make sure gcloud command is on our PATH
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1 CLOUDSDK_CORE_PROJECT=rachels-ghome

before_install:
- curl https://dl.google.com/dl/cloudsdk/release/install_google_cloud_sdk.bash | bash;
- gcloud components install cloud-datastore-emulator;
- gcloud components install beta;


before_script:
- gcloud beta emulators datastore start --no-legacy --host-port=localhost:8081 --no-store-on-disk &